### ISSUE TITLE
Kannst Du bitte einen requirements.txt hinzufuegen?

### ISSUE THREAD

**Issue by cwittern** [nunq/onleihe-dl#1]
Hallo,
auf meinem Ubuntu 22.04 System mit Python 3.11.4, bekomme ich nachdem ich mit pip die neueste Splinter version (0.19) installiert habe folgende Fehlermeldung:
`ImportError: cannot import name 'Config' from 'splinter' `
Ich vermute, dass das an einer falschen Version liegt, daher waere ich Dir dankbar, wenn Du einfach einen 'requirements.txt' erzeugst, damit mir pip die richtigen Versionen aller dependencies installiert.  Oder hast Du eine bessere Idee?

**Comment by nunq** [comment]
Achso ja die PYPI und github releases von splinter sind outdated, die Config Klasse gibts erst seit commit [30227103531e37b0d7932b087ab7d253803ee65c](https://github.com/cobrateam/splinter/commit/30227103531e37b0d7932b087ab7d253803ee65c) , deswegen einfach die master branch selber bauen. hab in 949a798 das requirements file hinzugefügt.
