### ISSUE TITLE
Adobe ID- Zur onleihe hinzufügen.

### ISSUE THREAD

**Issue by 0skxr** [nunq/onleihe-dl#2]
Hey 👋 

Weiss jemand wie man seine adobe id mit dem Onleihe konto verknüpft?

**Comment by nunq** [comment]
soweit ich weiß muss man die nicht direkt verknüpfen. ein adobe account wird lediglich benötigt, da manche medien die adobe adept drm benutzen. dieses projekt benutzt [libgourou](https://forge.soutade.fr/soutade/libgourou) um das zu handlen, das tut das gleiche wie wenn man sich auf einem tolino gerät mit dem adobe account anmeldet.
